root: true
ignorePatterns:
  - app.config.ts
  - scripts/**
  - babel.config.js
parserOptions:
  project: "tsconfig.json"
plugins:
  - "@typescript-eslint"
  - "prettier"
  - "unicorn"
  - "import"
extends:
  - "airbnb-typescript/base"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:unicorn/recommended"
  - "prettier"
rules:
  unicorn/numeric-separators-style: "off"
  unicorn/filename-case:
    - "error"
    - "case": "pascalCase"
  unicorn/expiring-todo-comments: "off"
  unicorn/no-null: "off"
  import/extensions: "off"
  unicorn/prefer-module: "off"
